// lockgen fija los paquetes de Debian que la base Debian de kindling (la de
// los constructores android y debian, internal/imagen) añade encima de
// debian:trixie-slim: resuelve las dependencias contra lo que
// ya trae la imagen (su /var/lib/dpkg/status), baja cada .deb, comprueba su
// sha256 con el índice y escribe internal/imagen/debian_lock.go.
//
//	go run ./internal/imagen/lockgen                  # arm64 y amd64
//	go run ./internal/imagen/lockgen -image debian@sha256:<índice>
//
// El índice (Packages.xz de trixie, trixie-updates y trixie-security) se baja
// por HTTPS y no se comprueba su firma: lo que queda fijado es el sha256 de
// cada .deb, y ese fichero es el que se revisa en el PR. Se ejecuta a mano al
// querer paquetes nuevos en la base; el constructor android nunca resuelve
// nada, solo baja lo fijado. (El constructor debian sí resuelve los paquetes
// de su receta, con internal/deb y los índices del snapshot de este lock.)
package main

import (
	"archive/tar"
	"bytes"
	"context"
	"crypto/sha256"
	"encoding/hex"
	"errors"
	"flag"
	"fmt"
	"go/format"
	"io"
	"net/http"
	"os"
	"path/filepath"
	"strings"
	"time"

	"github.com/juan52878911/kindling/internal/deb"
	"github.com/juan52878911/kindling/internal/oci"
	"github.com/juan52878911/kindling/internal/xz"
)

// Los que se piden (los mismos que build-image.sh: util-linux ya viene en la
// imagen) y los del 71-build-glibc-base.sh de siempre.
const defaultPackages = "iptables procps iproute2 dmsetup ca-certificates"

var suites = []struct{ base, suite string }{
	{"https://deb.debian.org/debian", "trixie"},
	{"https://deb.debian.org/debian", "trixie-updates"},
	{"https://security.debian.org/debian-security", "trixie-security"},
}

func main() {
	image := flag.String("image", "debian@sha256:a99cfc517144bc59b1978475ec53b46ecabec7e43635402ee5b77cc54cd1b20a", "debian:trixie-slim by index digest")
	archs := flag.String("arch", "arm64,amd64", "architectures")
	pkgs := flag.String("packages", defaultPackages, "packages to add (space separated)")
	out := flag.String("o", "internal/imagen/debian_lock.go", "output file")
	cache := flag.String("cache", filepath.Join(os.TempDir(), "kindling-lockgen"), "download cache")
	flag.Parse()
	if err := run(*image, strings.Split(*archs, ","), strings.Fields(*pkgs), *out, *cache); err != nil {
		fmt.Fprintln(os.Stderr, "lockgen:", err)
		os.Exit(1)
	}
}

func run(image string, archs, want []string, out, cache string) error {
	ref, index, ok := strings.Cut(image, "@")
	if !ok {
		return errors.New("-image must be repo@sha256:...")
	}
	var b bytes.Buffer
	b.WriteString("// Code generated by internal/imagen/lockgen; DO NOT EDIT.\n\npackage imagen\n\n")
	fmt.Fprintf(&b, "// Generado el %s con los paquetes %q.\n", time.Now().UTC().Format("2006-01-02"), strings.Join(want, " "))
	b.WriteString("var DebianLock = map[string]DebianBase{\n")
	snap := time.Now().UTC().Format("20060102T150405Z")
	for _, arch := range archs {
		c := &oci.Client{Cache: filepath.Join(cache, "oci"), Log: os.Stderr}
		img, err := c.Pull(context.Background(), ref, index, arch)
		if err != nil {
			return err
		}
		installed, err := installedPackages(img)
		if err != nil {
			return err
		}
		ix := deb.NewIndex()
		for _, s := range suites {
			if err := loadIndex(s.base, s.suite, arch, ix); err != nil {
				return err
			}
		}
		sel, err := ix.Resolve(want, installed)
		if err != nil {
			return fmt.Errorf("%s: %w", arch, err)
		}
		fmt.Fprintf(&b, "%q: {\n\tImage: %q, Index: %q, Manifest: %q, Snapshot: %q,\n\tPackages: []DebPin{\n", arch, ref, index, img.ManifestDigest, snap)
		for _, p := range sel {
			if err := fetch(p, filepath.Join(cache, "debs")); err != nil {
				return err
			}
			fmt.Fprintf(&b, "\t\t{%q, %q, %q, %q, %d},\n", p.Name, p.Version, p.Base+"/"+p.Filename, p.SHA256, p.Size)
			fmt.Fprintf(os.Stderr, "%s: %s %s (%d KiB)\n", arch, p.Name, p.Version, p.Size>>10)
		}
		b.WriteString("\t},\n},\n")
	}
	b.WriteString("}\n")
	src, err := format.Source(b.Bytes())
	if err != nil {
		return fmt.Errorf("gofmt: %w\n%s", err, b.String())
	}
	return os.WriteFile(out, src, 0o644)
}

func installedPackages(img *oci.Image) (map[string]string, error) {
	out := map[string]string{} // nombre y lo que provee -> versión
	for _, l := range img.Layers {
		rc, err := oci.OpenLayer(l)
		if err != nil {
			return nil, err
		}
		tr := tar.NewReader(rc)
		for {
			h, err := tr.Next()
			if errors.Is(err, io.EOF) {
				break
			}
			if err != nil {
				rc.Close()
				return nil, err
			}
			if strings.TrimPrefix(h.Name, "./") != "var/lib/dpkg/status" {
				continue
			}
			inst, err := deb.Installed(tr)
			if err != nil {
				rc.Close()
				return nil, err
			}
			for k, v := range inst {
				out[k] = v
			}
		}
		rc.Close()
	}
	if len(out) == 0 {
		return nil, errors.New("no /var/lib/dpkg/status in the image")
	}
	return out, nil
}

func get(url string) (b []byte, err error) {
	for try := 0; try < 4; try++ {
		if b, err = get1(url); err == nil {
			return b, nil
		}
		time.Sleep(time.Duration(try+1) * time.Second)
	}
	return nil, err
}

func get1(url string) ([]byte, error) {
	resp, err := (&http.Client{Timeout: 5 * time.Minute}).Get(url)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()
	if resp.StatusCode != 200 {
		return nil, fmt.Errorf("GET %s: %s", url, resp.Status)
	}
	return io.ReadAll(resp.Body)
}

func loadIndex(base, suite, arch string, ix *deb.Index) error {
	raw, err := get(fmt.Sprintf("%s/dists/%s/main/binary-%s/Packages.xz", base, suite, arch))
	if err != nil {
		return err
	}
	r, err := xz.NewReader(bytes.NewReader(raw))
	if err != nil {
		return err
	}
	return ix.Add(r, base)
}

func fetch(p *deb.Package, dir string) error {
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return err
	}
	dst := filepath.Join(dir, p.SHA256+".deb")
	if b, err := os.ReadFile(dst); err == nil {
		if s := sha256.Sum256(b); hex.EncodeToString(s[:]) == p.SHA256 {
			return nil
		}
	}
	b, err := get(p.Base + "/" + p.Filename)
	if err != nil {
		return err
	}
	if s := sha256.Sum256(b); hex.EncodeToString(s[:]) != p.SHA256 {
		return fmt.Errorf("%s: sha256 does not match the index", p.Filename)
	}
	return os.WriteFile(dst, b, 0o644)
}
