#!/bin/sh
# Sonda de "listo" de la imagen Android (api.GuestReadyProbe): 0 cuando
# Android terminó de arrancar.
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
v="$(android-sh getprop sys.boot_completed 2>/dev/null | tr -d '\r\n')"
[ "$v" = 1 ] && exit 0
echo "sys.boot_completed=${v:-?}"
exit 1
