#!/bin/sh
# Constructor "debian" del núcleo: Debian trixie fijada con los paquetes de la
# receta, todo en Go y sin root (internal/imagen). Ver docs/imagenes.md.
exec /usr/local/bin/kling builder debian "$@"
