// lockgen fija los paquetes de Debian que la base del constructor android
// añade encima de debian:trixie-slim: resuelve las dependencias contra lo que
// ya trae la imagen (su /var/lib/dpkg/status), baja cada .deb, comprueba su
// sha256 con el índice y escribe internal/android/debian_lock.go.
//
//	go run ./internal/android/lockgen                  # arm64 y amd64
//	go run ./internal/android/lockgen -image debian@sha256:<índice>
//
// El índice (Packages.xz de trixie, trixie-updates y trixie-security) se baja
// por HTTPS y no se comprueba su firma: lo que queda fijado es el sha256 de
// cada .deb, y ese fichero es el que se revisa en el PR. Se ejecuta a mano al
// querer paquetes nuevos; el constructor nunca resuelve nada, solo baja lo
// fijado.
package main

import (
	"archive/tar"
	"bytes"
	"context"
	"crypto/sha256"
	"encoding/hex"
	"errors"
	"flag"
	"fmt"
	"go/format"
	"io"
	"net/http"
	"os"
	"path/filepath"
	"sort"
	"strconv"
	"strings"
	"time"

	"github.com/juan52878911/kindling/internal/deb"
	"github.com/juan52878911/kindling/internal/oci"
	"github.com/juan52878911/kindling/internal/xz"
)

// Los que se piden (los mismos que build-image.sh: util-linux ya viene en la
// imagen) y los del 71-build-glibc-base.sh de siempre.
const defaultPackages = "iptables procps iproute2 dmsetup ca-certificates"

var suites = []struct{ base, suite string }{
	{"https://deb.debian.org/debian", "trixie"},
	{"https://deb.debian.org/debian", "trixie-updates"},
	{"https://security.debian.org/debian-security", "trixie-security"},
}

type pkg struct {
	para     deb.Paragraph
	name     string
	version  string
	filename string
	sha256   string
	size     int64
	base     string
}

func main() {
	image := flag.String("image", "debian@sha256:a99cfc517144bc59b1978475ec53b46ecabec7e43635402ee5b77cc54cd1b20a", "debian:trixie-slim by index digest")
	archs := flag.String("arch", "arm64,amd64", "architectures")
	pkgs := flag.String("packages", defaultPackages, "packages to add (space separated)")
	out := flag.String("o", "internal/android/debian_lock.go", "output file")
	cache := flag.String("cache", filepath.Join(os.TempDir(), "kindling-lockgen"), "download cache")
	flag.Parse()
	if err := run(*image, strings.Split(*archs, ","), strings.Fields(*pkgs), *out, *cache); err != nil {
		fmt.Fprintln(os.Stderr, "lockgen:", err)
		os.Exit(1)
	}
}

func run(image string, archs, want []string, out, cache string) error {
	ref, index, ok := strings.Cut(image, "@")
	if !ok {
		return errors.New("-image must be repo@sha256:...")
	}
	var b bytes.Buffer
	b.WriteString("// Code generated by internal/android/lockgen; DO NOT EDIT.\n\npackage android\n\n")
	fmt.Fprintf(&b, "// Generado el %s con los paquetes %q.\n", time.Now().UTC().Format("2006-01-02"), strings.Join(want, " "))
	b.WriteString("var debianLock = map[string]debianBase{\n")
	snap := time.Now().UTC().Format("20060102T150405Z")
	for _, arch := range archs {
		c := &oci.Client{Cache: filepath.Join(cache, "oci"), Log: os.Stderr}
		img, err := c.Pull(context.Background(), ref, index, arch)
		if err != nil {
			return err
		}
		installed, err := installedPackages(img)
		if err != nil {
			return err
		}
		avail := map[string]*pkg{}
		provides := map[string]string{}
		for _, s := range suites {
			if err := loadIndex(s.base, s.suite, arch, avail, provides); err != nil {
				return err
			}
		}
		sel, err := resolve(want, installed, avail, provides)
		if err != nil {
			return fmt.Errorf("%s: %w", arch, err)
		}
		fmt.Fprintf(&b, "%q: {\n\tImage: %q, Index: %q, Manifest: %q, Snapshot: %q,\n\tPackages: []debPin{\n", arch, ref, index, img.ManifestDigest, snap)
		for _, p := range sel {
			if err := fetch(p, filepath.Join(cache, "debs")); err != nil {
				return err
			}
			fmt.Fprintf(&b, "\t\t{%q, %q, %q, %q, %d},\n", p.name, p.version, p.base+"/"+p.filename, p.sha256, p.size)
			fmt.Fprintf(os.Stderr, "%s: %s %s (%d KiB)\n", arch, p.name, p.version, p.size>>10)
		}
		b.WriteString("\t},\n},\n")
	}
	b.WriteString("}\n")
	src, err := format.Source(b.Bytes())
	if err != nil {
		return fmt.Errorf("gofmt: %w\n%s", err, b.String())
	}
	return os.WriteFile(out, src, 0o644)
}

func installedPackages(img *oci.Image) (map[string]string, error) {
	out := map[string]string{} // nombre y lo que provee -> versión
	for _, l := range img.Layers {
		rc, err := oci.OpenLayer(l)
		if err != nil {
			return nil, err
		}
		tr := tar.NewReader(rc)
		for {
			h, err := tr.Next()
			if errors.Is(err, io.EOF) {
				break
			}
			if err != nil {
				rc.Close()
				return nil, err
			}
			if strings.TrimPrefix(h.Name, "./") != "var/lib/dpkg/status" {
				continue
			}
			ps, err := deb.ParseParagraphs(tr)
			if err != nil {
				rc.Close()
				return nil, err
			}
			for _, p := range ps {
				if !strings.Contains(p.Get("Status"), "installed") {
					continue
				}
				out[p.Get("Package")] = p.Get("Version")
				for _, grp := range deb.ParseDepends(p.Get("Provides")) {
					for _, r := range grp {
						out[r.Name] = p.Get("Version")
					}
				}
			}
		}
		rc.Close()
	}
	if len(out) == 0 {
		return nil, errors.New("no /var/lib/dpkg/status in the image")
	}
	return out, nil
}

func get(url string) (b []byte, err error) {
	for try := 0; try < 4; try++ {
		if b, err = get1(url); err == nil {
			return b, nil
		}
		time.Sleep(time.Duration(try+1) * time.Second)
	}
	return nil, err
}

func get1(url string) ([]byte, error) {
	resp, err := (&http.Client{Timeout: 5 * time.Minute}).Get(url)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()
	if resp.StatusCode != 200 {
		return nil, fmt.Errorf("GET %s: %s", url, resp.Status)
	}
	return io.ReadAll(resp.Body)
}

func loadIndex(base, suite, arch string, avail map[string]*pkg, provides map[string]string) error {
	raw, err := get(fmt.Sprintf("%s/dists/%s/main/binary-%s/Packages.xz", base, suite, arch))
	if err != nil {
		return err
	}
	r, err := xz.NewReader(bytes.NewReader(raw))
	if err != nil {
		return err
	}
	ps, err := deb.ParseParagraphs(r)
	if err != nil {
		return err
	}
	for _, p := range ps {
		name, ver := p.Get("Package"), p.Get("Version")
		if old, ok := avail[name]; ok && deb.CompareVersions(old.version, ver) >= 0 {
			continue
		}
		size, _ := strconv.ParseInt(p.Get("Size"), 10, 64)
		avail[name] = &pkg{para: p, name: name, version: ver, filename: p.Get("Filename"), sha256: p.Get("SHA256"), size: size, base: base}
		for _, grp := range deb.ParseDepends(p.Get("Provides")) {
			for _, rel := range grp {
				if _, ok := provides[rel.Name]; !ok {
					provides[rel.Name] = name
				}
			}
		}
	}
	return nil
}

// resolve cierra las dependencias (Depends y Pre-Depends, primera
// alternativa que exista; Recommends no, como --no-install-recommends).
func resolve(want []string, installed map[string]string, avail map[string]*pkg, provides map[string]string) ([]*pkg, error) {
	chosen := map[string]*pkg{}
	var order []*pkg
	var add func(name string, from string) error
	add = func(name, from string) error {
		if _, ok := installed[name]; ok {
			return nil
		}
		if _, ok := chosen[name]; ok {
			return nil
		}
		p := avail[name]
		if p == nil {
			if real, ok := provides[name]; ok {
				return add(real, from)
			}
			return fmt.Errorf("%s (needed by %s) is not in the archive", name, from)
		}
		chosen[name] = p
		for _, f := range []string{"Pre-Depends", "Depends"} {
			for _, grp := range deb.ParseDepends(p.para.Get(f)) {
				if satisfied(grp, installed, chosen) {
					continue
				}
				pick := ""
				for _, r := range grp {
					if avail[r.Name] != nil || provides[r.Name] != "" {
						pick = r.Name
						break
					}
				}
				if pick == "" {
					return fmt.Errorf("%s: no candidate for %v", name, grp)
				}
				if err := add(pick, name); err != nil {
					return err
				}
			}
		}
		order = append(order, p)
		return nil
	}
	for _, w := range want {
		if err := add(w, "request"); err != nil {
			return nil, err
		}
	}
	sort.SliceStable(order, func(i, j int) bool { return order[i].name < order[j].name })
	return order, nil
}

func satisfied(grp []deb.Relation, installed map[string]string, chosen map[string]*pkg) bool {
	for _, r := range grp {
		if _, ok := installed[r.Name]; ok {
			return true
		}
		if _, ok := chosen[r.Name]; ok {
			return true
		}
	}
	return false
}

func fetch(p *pkg, dir string) error {
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return err
	}
	dst := filepath.Join(dir, p.sha256+".deb")
	if b, err := os.ReadFile(dst); err == nil {
		if s := sha256.Sum256(b); hex.EncodeToString(s[:]) == p.sha256 {
			return nil
		}
	}
	b, err := get(p.base + "/" + p.filename)
	if err != nil {
		return err
	}
	if s := sha256.Sum256(b); hex.EncodeToString(s[:]) != p.sha256 {
		return fmt.Errorf("%s: sha256 does not match the index", p.filename)
	}
	return os.WriteFile(dst, b, 0o644)
}
